---
layout: page
title: "자연어 처리 - 정규표현식"
subtitle: "형태소 분석과 품사 태깅"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(reticulate)
use_condaenv("anaconda3")
# reticulate::repl_python()
```


# 영문 형태소 분석 {#pos-english}

`nltk.download()` 함수를 사용해서 필요한 기능을 다운로드 받는다.

- `nltk.download('averaged_perceptron_tagger')`
- `nltk.download('punkt')`

영문 형태소 분석기가 준비되었으면 [The quick brown fox jumps over the lazy dog](https://ko.wikipedia.org/wiki/The_quick_brown_fox_jumps_over_the_lazy_dog) 문장을 대상으로 명사를 추출해본다.
형태소 분석이 끝난 결과를 딕셔너리로 만들어서 이를 토큰화 과정을 마친 단어의 형태소를 list comprehension으로 명사만 추출한다.

```{python pos-english-dictionary}
import nltk
from pprint import pprint

eng_sentence =  ["The quick brown fox jumps over the lazy dog"]

def build_dictionary():
    dictionary = {}
    for sent in eng_sentence:
        pos_tags = nltk.pos_tag(nltk.word_tokenize(sent))
        for tag in pos_tags:
            value = tag[0]
            pos = tag[1]
            dictionary[value] = pos
    return dictionary

pos_dict = build_dictionary()

pprint(pos_dict)

nouns = [n for n, tag in pos_dict.items() if tag in ["NN","NNP"] ]
print(nouns)
```


# 국문 형태소 분석 [^kakao-pos] [^konlpy-pos] [^형태소분석표] {#pos-korean}

[^kakao-pos]: [한글 형태소 분석기 KKMA - with 카톡대화](https://ssoonidev.tistory.com/88)

[^konlpy-pos]: [KoNLPy Installation](http://konlpy.org/en/latest/install/)

[^형태소분석표]: [꼬꼬마 한국어 형태소 분석기](http://kkma.snu.ac.kr/documents/index.jsp)

한국어 형태소 분석기는 Kkma, Hannanum, Komoran, Mecab, Twitter 정도가 많이 알려져 있고, 각각 다른 특성이 있기 때문에 풀고자 하는 텍스트 데이터에 따라서 적절히 사용하면 좋다.
다만, MeCab의 경우 [RmecabKo 설치 - 맥(Mac)](https://statkclee.github.io/text/nlp-rmecabko-install.html)을 참조하여 R 환경에서 설치하고, 파이썬 환경 특히 KoNLPy `bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)`을 추가하여 설치해야 하는데 GCC에 의존하여 맥에서 설치가 되지 않는 경우 다음을 참조하여 설치과정을 마무리한다.


<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 10px;}
</style>
<div class = "blue">

**`MeCab_wrap.cxx:2982:10: fatal error: 'stdexcept' file not found` 오류**

맥 OSX 기본 컴파일러는 Apple LLVM 이라, 환경 변수에 GNU 를 설정하지 않고 `export CC=/usr/local/Cellar/gcc/9.1.0/bin/gcc-9` 명령어를 사용해서 MeCab 설치만 사용하고 자세한 설치 과정은 [OSX - Mojave 에서 mecab-python3 설치하기](https://medium.com/@jjeaby/osx-mojave-%EC%97%90%EC%84%9C-mecab-python3-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0-c007bcb19189) 블로그를 참조한다.

</div>

노무현 대통령 [전시작전 통제권 "부끄러운 줄 알아야지"](https://namu.wiki/w/%EB%B6%80%EB%81%84%EB%9F%AC%EC%9A%B4%20%EC%A4%84%20%EC%95%8C%EC%95%84%EC%95%BC%EC%A7%80) 연설 중 일부를 발췌하여 명사를 뽑아내보자.
이를 위해서 `Mecab()` 객체를 생성하고 이를 통해 특정 품사만 추출, 특히 명사만 추출해본다.


```{python pos-korean-dictionary}
from konlpy.tag import Kkma, Hannanum, Komoran, Mecab, Twitter

speech = '대한민국 군대들 지금까지 뭐 했노, 이기(야)! 나도 군대 갔다 왔고, 예비군 훈련[3]까지 다 받았는데, 심심하면 사람한테 세금 내라 하고, 불러다가 뺑뺑이 돌리고 훈련시키고 했는데, 거 위에 사람들은 뭐 했어! 작전통제권 자기들 나라 자기 군대 작전통제도 한 개 제대로 할 수 없는 군대를 맨들어 놔 놓고 “나 국방장관이요!” “나 참모총장이요!” 그렇게 별들 달고 끄드럭(거드럭)거리고 말았다는 얘깁니까? 그래서 작통권 회수하면 안 된다고 줄줄이 모여가 가지고 성명 내고. 자기들이 직무유기 아입니까? 부끄러운 줄 알아야지! 그렇게 수치스러운 일을들 하고…. 작통권 돌려받으면 우리 한국군들 잘해요. 경제도 잘하고, 문화도 잘하고, 영화도 잘하고, 한국 사람들이 외국 나가 보니깐 못 하는 게 없는데, 전화기도 잘 만들고, 차도 잘 만들고, 배도 잘 만들고 못 하는 게 없는데! 왜, 작전통제권만 왜 못 한다는 얘깁니까? 실제로요, 남북간에도 외교가 있고 한국과 중국 사이에도 외교가 있는데 — 북한의 유사시라는 건 뭐 있을 수도 없지만 전쟁도 유사시도 있을 수가 없지만 — 그러나 전쟁과 유사시를 항상 우리는 전제하고 준비하고 있는데 — 중국도 그렇게 준… 준비하지 않겠습니까? — 한국군이 작전통제권을 가지고 있을 때 북한과 우리가 대화하는 관계, 중국과 우리가 대화할 때, 외교상의 대화를 할 때, 동북아시아 안보 문제를 놓고 대화를 할 때, 그래도 한국이 말빨이 좀 있지 않겠습니까? 작전통제권도 없는 사람이, 민간시설에 폭격을 할 건지 안 할 건지 그것도 마음대로 결정 못 하고, 어느 시설에 폭격할 건지 그것도 지 맘대로 결정 못 하는 나라가 그 판에 가 가지고 중국한테 무슨 할 말이 있습니까…. 북한한테 무슨 할 말이 있어요? 이것은 외교상의 실리에 매우 중요한 문제 아니겠습니까?'

mecab = Mecab()

## 전체 품사 태깅
speech_pos = mecab.pos(speech)
pprint(speech_pos)

## 명사품사만 추출
nouns = [n for n, tag in speech_pos if tag in ["NNG","NNP"] ]
print(nouns)

## 명사 추출 메쏘드
mecab.nouns(speech)
```


