---
layout: page
title: "자연어 처리 - 정규표현식"
subtitle: "다양한 텍스트 데이터 가져오기"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(reticulate)
use_condaenv("anaconda3")
# reticulate::repl_python()
```


# `.pdf` 문서 가져오기 {#ingest-pdf}

## 영문 PDF 문서 {#ingest-english-pdf}

[PyPDF2](https://github.com/mstamy2/PyPDF2)는 순수 파이썬 PDF 라이브러리로 PDF 파일 각 페이지를 쪼개고 병합하고 짤래내고 변환시킬 수 있는 기능을 제공하고 있다. `pip install pypdf2` 명령어를 통해서 설치를 한후에 확장자가 `.pdf`를 갖는 파일을 불러들일 수 있다.
PDF 객체(`read_pdf`)를 만들고 나서 각 페이지내부에 포함된 텍스트를 추출한다. 

```{python ingest-pdf}
from PyPDF2 import PdfFileReader

pdf_file = open('data/sample.pdf', 'rb')
read_pdf = PdfFileReader(pdf_file)

text = []
for i in range(0,read_pdf.getNumPages()-1):
    text.append(read_pdf.getPage(i).extractText())

print(r'불러온 PDF 파일: \n',text)
```

이를 함수로 작성하여 `get_text_pdf()`로 제작하여 PDF파일에 포함된 텍스트를 추출한다.

```{python ingest-pdf-function}
def get_text_pdf(pdf_filename):
    pdf_file = open(pdf_filename, 'rb')
    read_pdf = PdfFileReader(pdf_file)
    ## PDF 텍스트 결과
    pdf_text = []
    ## PDF 텍스트 추출
    for i in range(0, read_pdf.getNumPages()-1):
        pdf_text.append(read_pdf.getPage(i).extractText())
     # 개행문자 결합
    return '\n'.join(pdf_text)  

print(r'불러온 PDF 파일: \n', get_text_pdf('data/sample.pdf'))
```

## 한글 PDF 문서 {#ingest-korean-pdf}

- [pdfminer](https://github.com/pdfminer/pdfminer.six/)
    - "CJK languages and vertical writing scripts support."
    - 많은 기능중에 CJK 언어를 활용할 수 있다.
- PyMuPDF
- [Tika, PDF파일에서 텍스트 내용 파싱](https://nearman.tistory.com/entry/8-%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%9C%BC%EB%A1%9C-PDF%ED%8C%8C%EC%9D%BC-%EC%9D%BD%EC%96%B4%EC%98%A4%EA%B8%B0-PDF%ED%8C%8C%EC%9D%BC%EC%97%90%EC%84%9C-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EB%82%B4%EC%9A%A9-%ED%8C%8C%EC%8B%B1): 자바 의존성을 갖고 있으며, `pip install tika` 명령어로 설치 후 사용, 느리다는 평가가 많음.

`PyPDF`를 사용하게 되면 CJK 언어로 된 `.pdf` 파일에서 한국어를 추출할 경우 제대로 추출이 되고 있지 않다.

```{python ingest-hangul-pdf}
pdf_file = open('data/hangul_sample.pdf', 'rb')
read_pdf = PdfFileReader(pdf_file)

text = []
for i in range(0,1):
    text.append(read_pdf.getPage(i).extractText())

print(r'불러온 PDF 파일: \n',text)
```

[extraction of text from pdf with pdfminer gives multiple copies](https://stackoverflow.com/questions/26748788/extraction-of-text-from-pdf-with-pdfminer-gives-multiple-copies) 코드를 참조하여 `pdfminer` 라이브러리를 사용해서 한국어로된 PDF 파일에서 한글을 잘 추출할 수 있는 방법도 있음이 확인되었다.

```{python ingest-hangul-pdfminer}
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from io import StringIO

def convert_pdf_to_txt(path):
    rsrcmgr = PDFResourceManager()
    retstr = StringIO()
    codec = 'utf-8'
    laparams = LAParams()
    device = TextConverter(rsrcmgr, retstr, codec=codec, laparams=laparams)
    fp = open(path, 'rb')
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    password = ""
    maxpages = 0
    caching = True
    pagenos=set()
    
    for page in PDFPage.get_pages(fp, pagenos, maxpages=maxpages, password=password,caching=caching, check_extractable=True):
        interpreter.process_page(page)
        text = retstr.getvalue()

    fp.close()
    device.close()
    retstr.close()
    return text
    
extracted_text = convert_pdf_to_txt('data/hangul_sample.pdf')
print(extracted_text)
```

# `.docx` 워드문서 가져오기 {#ingest-word}

`pip install python-docx` 명령어로 파이썬에서 MS 워드 문서를 불러오기 위한 라이브러리를 설치한다. [나무위키 - 서시(윤동주)](https://namu.wiki/w/%EC%84%9C%EC%8B%9C(%EC%9C%A4%EB%8F%99%EC%A3%BC)) 내용 일부를 복사하여 "윤동주.docx" 파일명으로 저장을 시킨다.
이를 `docx` 라이브러리를 사용해서 파이썬에서 자연어 처리를 할 수 있는 텍스트 형태로 가공하여 뽑아낸다.

```{python ingest-word-document}
import docx

doc = docx.Document('data/윤동주.docx')
word_text = []
for para in doc.paragraphs:
    word_text.append(para.text)

print(word_text)    
```

앞서 제작한 코드를 함수로 `get_word_text()` 함수로 제작하여 MS 워드 문서를 넣으면 텍스트를 추출하도록 코드를 제작한다.

```{python ingest-word-document-function}
def get_word_text(word_filename):
    doc = docx.Document(word_filename)
    word_text = []
    for para in doc.paragraphs:
        word_text.append(para.text)
    return '\n'.join(word_text)

word_text = get_word_text('data/윤동주.docx')
print(word_text)
```

# `.hwp` 아래한글 문서 가져오기 [^hwp-ingest] [^pyhwp-tutorial] {#ingest-hwp}

[^hwp-ingest]: [웹으로 말하기 (2014-03-27), "리눅스에서 한글 파일(hwp) 파일 변환해서 읽기"](https://mytory.net/archives/12797)

[^pyhwp-tutorial]: [HWP 파일을 다양한 확장자로 변환하기 - 1](https://suspected.tistory.com/entry/pyhwp-HWP-%ED%8C%8C%EC%9D%BC%EC%9D%84-%EB%8B%A4%EC%96%91%ED%95%9C-%ED%99%95%EC%9E%A5%EC%9E%90%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%98%EA%B8%B0)

[pyhwp](https://github.com/mete0r/pyhwp) 라이브러리가 0.1b12 버젼부터 즉 2019년 4월 8일부터 파이썬3을 지원하기 시작했다.
자세한 사항은 [Python 3 지원 #112](https://github.com/mete0r/pyhwp/issues/112)을 참조하여 HWP 파일을 `.txt` 파일로 변환시킨다.

먼저 `os.system()` 메쏘드를 사용해서 쉘명령어를 사용해서 `.hwp` 파일을 `.txt` 파일로 변환시킨다. 이제 일반 평문 텍스트로 한글파일이 변환되었기에 이를 파이썬으로 불러 읽어들인다.

```{python ingest-hwp}
import os

## 쉘에서 `hwp5txt` 변환실행
hwp2txt_cmd = 'hwp5txt data/발명진흥법.hwp > data/발명진흥법.txt'
os.system(hwp2txt_cmd)

## HWP에서 TXT 변환파일 텍스트 확인
hwp_txt = open("data/발명진흥법.txt", "r")
print(hwp_txt.read())
```


